steps:
  - label: "Tests"
    key: "test"
    command:
      - git config --global --unset url.ssh://git@github.com/.insteadOf https://github.com/
      - npm install --no-audit
      - npm test
    agents:
      queue: "node14"

  - label: "Publish Library"
    key: "publish"
    command:
      - git config --global user.email "sdom@involves.com"
      - git config --global user.name "Buildkite"
      - npm version patch
      - git push -u origin master --tags
    agents:
      queue: "node14"
    depends_on:
      - "test"
    if: build.branch == "master"